// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocationByName(arg1) {
  return window['go']['main']['App']['GetLocationByName'](arg1);
}

export function GetWeatherByCity(arg1) {
  return window['go']['main']['App']['GetWeatherByCity'](arg1);
}

export function GetWeatherByCoords(arg1, arg2) {
  return window['go']['main']['App']['GetWeatherByCoords'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
