// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLocationByName(arg1:string):Promise<Array<main.LocationData>>;

export function GetWeatherByCity(arg1:string):Promise<main.WeatherData>;

export function GetWeatherByCoords(arg1:number,arg2:number):Promise<main.WeatherData>;

export function Greet(arg1:string):Promise<string>;
